---
title: "examples"
author: "yuqi"
date: "2026-03-07"
output: html_document
---
```{r}
dirs <- c(
  "/Users/yuqi/Documents/GitHub/TFMseg/Method_funcs",
  "/Users/yuqi/Documents/GitHub/TFMseg/Simulation"
)

for (d in dirs) {
  r_files <- list.files(d, pattern = "\\.R$", full.names = TRUE)
  for (f in r_files) source(f)
}
```

# Detection results

```{r}
Ts <- c(400, 800, 1600, 3200)[1:4]

dim_obs_list <- list(c(10, 10, 10), c(20, 20, 20), c(10, 20, 40), c(10, 10, 100))[1]

simulation_settings <- unlist(
  lapply(dim_obs_list, function(dobs) {
    lapply(Ts, function(Time) { list(Time = Time, dim_obs = dobs, dim_latent = c(3, 3, 3))}) }),
  recursive = FALSE
)

```



```{r}
tab_1 <- simu_ret(methods = c("TFMseg", "LR")[1], 
                  simu_set_detect = simulation_settings,
                  data_setting = "s0", dep = TRUE, theta_coef = c(0,0,0), r_hat = NULL)
tab_1$table

multi_hist(
  tab_1,
  Time_list = c(400, 800, 1600, 3200)[1],
  dim_obs_list = list(c(10,10,10), c(20,20,20), c(10,20,40), c(10,10,100))[1],
  theta_coef = c(0.25, 0.5, 0.75),
  source_names = c("TFMseg", "LR")[1]
)

```


```{r}
tab_2 <- simu_ret(methods = c("TFMseg", "LR"), 
                  simu_set_detect = simulation_settings,
                  data_setting = "s1", dep = TRUE, theta_coef = c(0.25,0.5,0.75), r_hat = NULL, nrep = 50)
tab_2$table

tab_2_good <- extract_accurate(tab_2, source_names = c("TFMseg","LR"), exact_3_change = TRUE, sep_scaled = 0.1)

multi_hist(
  tab_2, # all
  tab_2_good, # filtered
  Time_list = c(400, 800, 1600, 3200),
  dim_obs_list =  list(c(10,10,10), c(20,20,20), c(10,20,40), c(10,10,100))[1],
  theta_coef = c(0.25, 0.5, 0.75),
  source_names = c("TFMseg", "LR"),
  compare_dataset = TRUE,
  dataset_names = c("All", "Accurate"),
  dataset_position = "identity", 
  binwidth = 0.08
)


```


```{r}
multi_hist(
  tab_2,
  Time_list = c(400, 800, 1600, 3200),
  dim_obs_list = list(c(10,10,10),
                      c(20,20,20), 
                      c(10,20,40), 
                      c(10,10,100))[1],
  theta_coef = c(0.25, 0.5, 0.75),
  source_names = c("TFMseg", "LR")
)
```


# Identification

```{r}
tab_3 <- id_modes_1(cp_est_df = tab_2_good$cp_est_df,
                    dim_obs_list = list(c(10,10,10), c(20,20,20), c(10,20,40), c(10,10,100))[1],
                    Time_list = c(400, 800, 1600, 3200)[1],
                    theta_coef = c(0.25,0.5,0.75), r_hat = c(3,3,3), use_true_cp = FALSE,
                    data_setting = "s1")


tab_3$`T=400|dim=10x10x10|set=s2`$zeta_by_cp


tab_3_pool <- pool_by_cp(tab_3)


plot_zeta_mode(tab_3_pool[[1]], y = "ratio_Tp", low_mode = 1, low_bound = "q05", up_mode = 2, up_bound  = "q95")
plot_zeta_mode(tab_3_pool[[2]], y = "ratio_Tp", low_mode = 2, low_bound = "q05", up_mode = 3, up_bound  = "q95")
plot_zeta_mode(tab_3_pool[[3]], y = "ratio_Tp", low_mode = 2, low_bound = "q05", up_mode = 1, up_bound  = "q95")
plot_zeta_mode(tab_3_pool[[3]], y = "ratio_Tp", low_mode = 3, low_bound = "q05", up_mode = 1, up_bound  = "q95")


eval_all(tab_3, id_thd_coef = 3, true_mode_list = list(c(1), c(2), c(3)))
```



